{
    'name': 'My Module',
    'version': '1.0',
    'depends': ['base'],
    'data': [
        'views/my_module_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'qweb': [],
    'license': 'AGPL-3',
    'author': 'Your Name',
    'website': 'https://www.example.com',
    'description': 'My module description',
    'category': 'Uncategorized',
    'sequence': 1,
    'demo': [],
    'images': [],
    'external_dependencies': {},
    'depends': ['base'],
    'data': [
        'views/my_module_views.xml',
    ],
    'demo': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'external_dependencies': {},
    'qweb': [],
    'license': 'AGPL-3',
    'summary': 'My modulede description',
    'sequence': 1,
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': True,
    'external_dependencies': {},
    'qweb': [],
    'license': 'AGPL-3',
    'summary': 'My module description',
    'description': 'My module description',
    'category': 'Uncategorized',
    'depends': ['base'],
    'data': [
        'views/my_module_views.xml',
    ],
    'demo': [],
    'test': [],
    'post_init_hook': 'post_init_hook',
}